### 등록
POST {{api}}/member
Content-Type: application/json

{
  "name": "KNJ",
  "phoneNumber": "01012341234",
  "email": "namjunemy@gmail.com",
  "memberType": "admin"
}


### 조회
GET {{api}}/members
Content-Type: application/json

